I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 61, in script call
    call sotry1 from _call_sotry1
  File "game/sotry1.rpy", line 13, in script
    $ char10 = character[9][CharName]
  File "game/sotry1.rpy", line 13, in <module>
    $ char10 = character[9][CharName]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 61, in script call
    call sotry1 from _call_sotry1
  File "game/sotry1.rpy", line 13, in script
    $ char10 = character[9][CharName]
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/sotry1.rpy", line 13, in <module>
    $ char10 = character[9][CharName]
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Linux-5.15.74-3-MANJARO-x86_64-with-glibc2.36 x86_64
Ren'Py 8.0.3.22090809
pain hell
Wed Oct 26 10:10:35 2022
