I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 62, in script call
    call sotry1 from _call_sotry1
  File "game/sotry1.rpy", line 55, in script
    scene bg train with dissovle
  File "game/sotry1.rpy", line 55, in <module>
    scene bg train with dissovle
NameError: name 'dissovle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 62, in script call
    call sotry1 from _call_sotry1
  File "game/sotry1.rpy", line 55, in script
    scene bg train with dissovle
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 1654, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/karl/Desktop/renpy-8.0.3-sdk/renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/sotry1.rpy", line 55, in <module>
    scene bg train with dissovle
NameError: name 'dissovle' is not defined

Linux-5.15.76-1-MANJARO-x86_64-with-glibc2.36 x86_64
Ren'Py 8.0.3.22090809
pain hell
Thu Nov  3 09:32:19 2022
